# docker-compose.yml

services:
  knx-garage-wled:
    image: ghcr.io/noschvie/knx-garage-wled:development
    container_name: knx-garage-wled
    restart: unless-stopped
    env_file:
      - .env
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
